const drops = {
	// units
	'units-ultra-rare': [
		{ code: 'u0001-4-commando1', probability: 0.8 },
		{ code: 'u0001-4-commando2', probability: 0.8 },
		{ code: 'u0001-4-commando3', probability: 0.8 },
		{ code: 'u0001-4-commando4', probability: 0.8 },
		{ code: 'u0001-4-commando5', probability: 0.8 },
		{ code: 'u0001-4-commando6', probability: 0.8 },
		{ code: 'u0001-4-commando7', probability: 0.8 },
		{ code: 'u0001-4-cupcake', probability: 1 },
		{ code: 'u0001-5-cane', probability: 1 },
		{ code: 'u0001-3-kopi', probability: 1 },
		{ code: 'u0001-3-chai', probability: 1 },
		{ code: 'u0001-3-choco', probability: 1 },
		{ code: 'u0001-3-milky', probability: 1 },
		{ code: 'u0001-3-sencha', probability: 1 },
		{ code: 'u0001-5-queenlollie', probability: 1 },
	],
	'units-rare': [
		{ code: 'u0001-3-bloo', probability: 1 },
		{ code: 'u0001-3-vinia', probability: 1 },
		{ code: 'u0001-3-oran', probability: 1 },
		{ code: 'u0001-3-spritz', probability: 1 },
		{ code: 'u0001-3-soda', probability: 1 },
		{ code: 'u0001-1-benny', probability: 1 },
		{ code: 'u0001-4-slabb', probability: 1 },
		{ code: 'u0001-4-crimson', probability: 1 },
		{ code: 'u0001-4-violet', probability: 1 },
		{ code: 'u0001-3-rose', probability: 1 },
		{ code: 'u0001-2-ogre', probability: 1 },
		{ code: 'u0001-2-jet', probability: 1 },
		{ code: 'u0001-1-pete', probability: 1 },
		{ code: 'u0001-2-coco', probability: 1 },
		{ code: 'u0001-5-bibly', probability: 1 },
		{ code: 'u0001-2-zerosix', probability: 1 },
		{ code: 'u0001-2-tom', probability: 1 },
		{ code: 'u0001-1-zoe', probability: 1 },
		{ code: 'u0001-3-zar', probability: 1 },
		{ code: 'u0001-3-corpus', probability: 1 },
		{ code: 'u0001-3-arcus', probability: 1 },
		{ code: 'u0001-3-pismud', probability: 1 },
		{ code: 'u0001-4-ruby', probability: 1 },
		{ code: 'u0001-3-timmy', probability: 1 },
		{ code: 'u0001-5-popo', probability: 1 },
		{ code: 'u0001-3-poki', probability: 1 },
		{ code: 'u0001-1-skye', probability: 1 },
		{ code: 'u0001-2-momoka', probability: 1 },
		{ code: 'u0001-3-redford', probability: 1 },
		{ code: 'u0001-4-sylvia', probability: 1 },
		{ code: 'u0001-4-ginger', probability: 1 },
		{ code: 'u0001-4-lily', probability: 1 },
		{ code: 'u0001-4-chizu', probability: 1 },
		{ code: 'u0001-5-rook', probability: 1 },
		{ code: 'u0001-5-rookia', probability: 1 },
		{ code: 'u0001-4-ebony', probability: 1 },
		{ code: 'u0001-5-pumpee', probability: 1 },
		{ code: 'u0001-5-kor', probability: 1 },
		{ code: 'u0001-5-boowee', probability: 1 },
		{ code: 'u0001-5-mumay', probability: 1 },
		{ code: 'u0001-5-dave', probability: 1 },
		{ code: 'u0001-5-stain', probability: 1 },
		{ code: 'u0001-5-gretchen', probability: 1 },
		{ code: 'u0001-5-glinda', probability: 1 },
		{ code: 'u0001-5-jack', probability: 1 },
	],
	'units-common': [
		{ code: 'u0001-1-macho', probability: 1 },
		{ code: 'u0001-2-toto', probability: 1 },
		{ code: 'u0001-3-twinkle', probability: 1 },
		{ code: 'u0001-4-vispi', probability: 1 },
		{ code: 'u0001-5-drat', probability: 1 },
		{ code: 'u0001-4-antonio', probability: 1 },
		{ code: 'u0001-4-bumpier', probability: 1 },
		{ code: 'u0001-4-tabi', probability: 1 },
		{ code: 'u0001-5-electopus', probability: 1 },
		{ code: 'u0001-5-santelmo', probability: 1 },
		{ code: 'u0001-5-multo', probability: 1 },
		{ code: 'u0001-5-kelvin', probability: 1 },
		{ code: 'u0001-5-blanko', probability: 1 },
		{ code: 'u0001-5-prickles', probability: 1 },
		{ code: 'u0001-5-crack9', probability: 1 },
		{ code: 'u0001-5-robia', probability: 1 },
		{ code: 'u0001-5-barbell', probability: 1 },
		{ code: 'u0001-5-wap', probability: 1 },
	],
	// gear
	'gear-special': [
		{ code: 'eq_wpn_0001', probability: 1 },
		{ code: 'eq_acc_0101', probability: 1 },
		{ code: 'eq_amr_0061', probability: 1 },
	],
	'gear-rare': [
		{ code: 'eq_wpn_0001', probability: 1 },
		{ code: 'eq_acc_0101', probability: 1 },
		{ code: 'eq_amr_0061', probability: 1 },
	],
	'gear-normal': [
		{ code: 'eq_wpn_0001', probability: 1 },
		{ code: 'eq_acc_0101', probability: 0.2 },
		{ code: 'eq_amr_0061', probability: 0.3 },
	],
};

export const getCurrentGacha = async () => {
	return {
		drops,
		units: [
			{
				id: 'units-ultra-rare',
				thumb: '/assets/gacha/units1.thumb.svg',
				image: '/assets/gacha/units1.svg',
				imageBg: 'linear-gradient(180deg, blue, red)',
				options: [
					{ type: 'ticket', pulls: '1', cost: '5' },
					{ type: 'ruby', pulls: '6+1', cost: '300' },
				],
			},
			{
				id: 'units-rare',
				thumb: '/assets/gacha/units2.thumb.svg',
				image: '/assets/gacha/units2.svg',
				imageBg: 'linear-gradient(180deg, yellow, brown)',
				options: [
					{ type: 'ticket', pulls: '1', cost: '2' },
					{ type: 'ruby', pulls: '5+1', cost: '100' },
				],
			},
			// {
			// 	id: 'units-common',
			// 	thumb: '/assets/gacha/units3.thumb.svg',
			// 	image: '/assets/gacha/units3.svg',
			// 	imageBg: 'linear-gradient(180deg, green, #4F4)',
			// 	options: [
			// 		{
			// 			type: 'friendPoints',
			// 			pulls: '1',
			// 			cost: '100',
			// 			limit: 10,
			// 		},
			// 		{
			// 			type: 'friendPoints',
			// 			pulls: '5+1',
			// 			cost: '500',
			// 			limit: 2,
			// 		},
			// 	],
			// },
			// {
			// 	type: 'purple',
			// 	thumb: '/assets/gacha/units4.thumb.svg',
			// 	image: '/assets/gacha/units4.svg',
			// 	imageBg: 'linear-gradient(180deg, purple, white)',
			// },
			// {
			// 	type: 'yellow',
			// 	thumb: '/assets/gacha/units5.thumb.svg',
			// 	image: '/assets/gacha/units5.svg',
			// 	imageBg: 'linear-gradient(180deg, aqua, teal)',
			// },
		],
		gear: [
			{
				id: 'gear-special',
				name: 'SPECIAL',
				thumb: '/assets/gacha/gear1.thumb.svg',
				image: '/assets/gacha/gear1.svg',
				imageBg: 'linear-gradient(180deg, blue, red)',
				options: [
					{ type: 'ruby', pulls: '1', cost: '40' },
					{ type: 'ruby', pulls: '5+1', cost: '200' },
				],
			},
			{
				id: 'gear-rare',
				name: 'RARE',
				thumb: '/assets/gacha/gear2.thumb.svg',
				image: '/assets/gacha/gear2.svg',
				imageBg: 'linear-gradient(180deg, yellow, brown)',
				options: [{ type: 'ruby', pulls: '5+1', cost: '100' }],
			},
			// {
			// 	id: 'gear-normal',
			// 	name: 'NORMAL',
			// 	thumb: '/assets/gacha/gear3.thumb.svg',
			// 	image: '/assets/gacha/gear3.svg',
			// 	imageBg: 'linear-gradient(180deg, green, #4F4)',
			// 	options: [
			// 		{ type: 'friendPoints', pulls: '1', cost: '40' },
			// 		{ type: 'friendPoints', pulls: '5+1', cost: '200' },
			// 	],
			// },

			// {
			// 	type: 'purple',
			// 	thumb: '/assets/gacha/gear4.thumb.svg',
			// 	image: '/assets/gacha/gear4.svg',
			// 	imageBg: 'linear-gradient(180deg, purple, white)',
			// },
			// {
			// 	type: 'yellow',
			// 	thumb: '/assets/gacha/gear5.thumb.svg',
			// 	image: '/assets/gacha/gear5.svg',
			// 	imageBg: 'linear-gradient(180deg, aqua, teal)',
			// },
		],
	};
};
