export const materials = {
	'ev-101': {
		name: 'Low Strength Potion',
		image: '/assets/materials/ev-101.png',
		grade: 1,
		extractCoins: 100,
		extractMinerals: '1 - 0 - 0',
		craftMinerals: '1 - 0 - 0',
		craftHours: 0.25,
	},
	'ev-102': {
		name: 'Mid Strength Potion',
		image: '/assets/materials/ev-102.png',
		grade: 2,
		extractCoins: 400,
		extractMinerals: '7 - 0 - 0',
		craftMinerals: '7 - 0 - 0',
		craftHours: 0.5,
	},
	'ev-103': {
		name: 'High Strength Potion',
		image: '/assets/materials/ev-103.png',
		grade: 3,
		extractCoins: 1600,
		extractMinerals: '30 - 0 - 0',
		craftMinerals: '30 - 0 - 0',
		craftHours: 0.75,
	},

	'ev-201': {
		name: 'Low Agility Potion',
		image: '/assets/materials/ev-201.png',
		grade: 1,
		extractCoins: 100,
		extractMinerals: '1 - 0 - 0',
		craftMinerals: '1 - 0 - 0',
		craftHours: 0.25,
	},
	'ev-202': {
		name: 'Mid Agility Potion',
		image: '/assets/materials/ev-202.png',
		grade: 2,
		extractCoins: 400,
		extractMinerals: '7 - 0 - 0',
		craftMinerals: '7 - 0 - 0',
		craftHours: 0.5,
	},
	'ev-203': {
		name: 'High Agility Potion',
		image: '/assets/materials/ev-203.png',
		grade: 3,
		extractCoins: 1600,
		extractMinerals: '30 - 0 - 0',
		craftMinerals: '30 - 0 - 0',
		craftHours: 0.75,
	},

	'ev-301': {
		name: 'Low Intelligence Potion',
		image: '/assets/materials/ev-301.png',
		grade: 1,
		extractCoins: 100,
		extractMinerals: '1 - 0 - 0',
		craftMinerals: '1 - 0 - 0',
		craftHours: 0.25,
	},
	'ev-302': {
		name: 'Mid Intelligence Potion',
		image: '/assets/materials/ev-302.png',
		grade: 2,
		extractCoins: 400,
		extractMinerals: '7 - 0 - 0',
		craftMinerals: '7 - 0 - 0',
		craftHours: 0.5,
	},
	'ev-303': {
		name: 'High Intelligence Potion',
		image: '/assets/materials/ev-303.png',
		grade: 3,
		extractCoins: 1600,
		extractMinerals: '30 - 0 - 0',
		craftMinerals: '30 - 0 - 0',
		craftHours: 0.75,
	},
};
