import { listAvailableUnits } from '../utils/units.js';
import { getAllThumbnails } from '../visuals/assets/character.js';

//prettier-ignore
export const getCollectionOLD = async () => [
	{ displayName: 'Raze', level: 145, mineralCost: 1000, stars: 3, collected: true },
	{ displayName: 'Inferno', level: 150, mineralCost: 1200, stars: 4, collected: true },
	{ displayName: 'Steve', level: 140, mineralCost: 800, stars: 2, collected: true },
	{ displayName: 'Tom', level: 120, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Jerry', level: 130, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Anna', level: 110, mineralCost: 500, stars: 1, collected: false },
	{ displayName: 'Elsa', level: 160, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Olaf', level: 100, mineralCost: 400, stars: 1, collected: false },
	{ displayName: 'Kristoff', level: 170, mineralCost: 1600, stars: 5, collected: true },
	{ displayName: 'Sven', level: 180, mineralCost: 1800, stars: 5, collected: true },
	{ displayName: 'Rapunzel', level: 150, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Ariel', level: 155, mineralCost: 1200, stars: 4, collected: true },
	{ displayName: 'Belle', level: 140, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Cinderella', level: 135, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Aurora', level: 145, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Mulan', level: 150, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Merida', level: 130, mineralCost: 500, stars: 1, collected: false },
	{ displayName: 'Pocahontas', level: 125, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Moana', level: 160, mineralCost: 1200, stars: 4, collected: true },
	{ displayName: 'Tiana', level: 140, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Snow White', level: 100, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Jasmine', level: 150, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Aladdin', level: 155, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Hercules', level: 145, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Mickey', level: 130, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Minnie', level: 125, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Goofy', level: 120, mineralCost: 700, stars: 2, collected: true },
	{ displayName: 'Donald', level: 135, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Daisy', level: 130, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Pluto', level: 115, mineralCost: 1200, stars: 4, collected: true },
	{ displayName: 'Simba', level: 145, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Nala', level: 140, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Scar', level: 150, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Mufasa', level: 155, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Timon', level: 120, mineralCost: 500, stars: 1, collected: false },
	{ displayName: 'Pumbaa', level: 125, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Zazu', level: 110, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Rafiki', level: 140, mineralCost: 800, stars: 2, collected: true },
	{ displayName: 'Shenzi', level: 130, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Banzai', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Ed', level: 115, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Woody', level: 150, mineralCost: 1000, stars: 3, collected: true },
	{ displayName: 'Buzz', level: 155, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Jessie', level: 145, mineralCost: 800, stars: 2, collected: true },
	{ displayName: 'Bullseye', level: 130, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Rex', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Hamm', level: 120, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Slinky', level: 135, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Bo Peep', level: 130, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Forky', level: 115, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Lotso', level: 160, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Mr. Potato Head', level: 145, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Mrs. Potato Head', level: 140, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Andy', level: 150, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Zurg', level: 160, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Gabby Gabby', level: 140, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Duke Caboom', level: 130, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Giggle McDimples', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Bo', level: 120, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Ken', level: 135, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Barbie', level: 130, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Stinky Pete', level: 115, mineralCost: 800, stars: 2, collected: true },
	{ displayName: 'Trixie', level: 160, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Buttercup', level: 145, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Dolly', level: 140, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Peas-in-a-Pod', level: 150, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Chuckles', level: 155, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Wheezy', level: 145, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Rocky Gibraltar', level: 130, mineralCost: 600, stars: 1, collected: true },
	{ displayName: 'Lenny', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Booster', level: 120, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'XR', level: 135, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Mirage', level: 130, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Nessus', level: 115, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Amalthea', level: 160, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Leo', level: 145, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Hydra', level: 140, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Apollo', level: 150, mineralCost: 1000, stars: 3, collected: true },
	{ displayName: 'Ares', level: 155, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Hera', level: 145, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Gemma', level: 115, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Athena', level: 130, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Hermes', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Hades', level: 120, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Zeus', level: 135, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Poseidon', level: 130, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Demeter', level: 115, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Hestia', level: 160, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Dionysus', level: 145, mineralCost: 700, stars: 2, collected: true },
	{ displayName: 'Artemis', level: 140, mineralCost: 1400, stars: 5, collected: true },
	{ displayName: 'Hephaestus', level: 150, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Persephone', level: 155, mineralCost: 1200, stars: 4, collected: false },
	{ displayName: 'Kratos', level: 145, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Pandora', level: 130, mineralCost: 600, stars: 1, collected: false },
	{ displayName: 'Prometheus', level: 125, mineralCost: 700, stars: 2, collected: false },
	{ displayName: 'Epimetheus', level: 120, mineralCost: 1400, stars: 5, collected: false },
	{ displayName: 'Helios', level: 135, mineralCost: 1000, stars: 3, collected: false },
	{ displayName: 'Selene', level: 130, mineralCost: 1200, stars: 4, collected: true },
	{ displayName: 'Eos', level: 115, mineralCost: 800, stars: 2, collected: false },
	{ displayName: 'Iris', level: 160, mineralCost: 600, stars: 1, collected: false }
];

export const getCollection = async () => {
	const collection = listAvailableUnits();
	const thumbnails = await getAllThumbnails();
	for (const unit of collection) {
		//TODO: mark whether or not user has this
		unit.image = thumbnails[unit.code];
		unit.collected = false;
	}
	return collection;
};
